-- Example of how UUIDs are stored in PostgreSQL
-- This is automatically handled by JPA/Hibernate

-- Table structure (auto-generated by Hibernate)
CREATE TABLE users (
    id UUID PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

-- Example UUID values that will be generated:
-- 123e4567-e89b-12d3-a456-426614174000
-- 987fcdeb-51a2-43d1-9f12-345678901234
-- 550e8400-e29b-41d4-a716-446655440000

-- Query examples:
-- SELECT * FROM users WHERE id = '123e4567-e89b-12d3-a456-426614174000'::UUID;
-- INSERT INTO users (id, username, email, password) VALUES (gen_random_uuid(), 'john_doe', 'john@example.com', 'hashed_password');

-- UUID functions in PostgreSQL:
-- gen_random_uuid() - generates a random UUID
-- uuid_generate_v4() - generates version 4 UUID (if uuid-ossp extension is enabled) 